### ISSUE TITLE
History Back Does Not Work

### ISSUE THREAD

**Issue by derek-knox** [nareshbhatia/mobx-shop#1]
Unsure if this is a mobx-shop issue or mobx-state-router itself.
Reference Tweet: https://twitter.com/NareshJBhatia/status/955285702421417984

*Expected behavior and actual behavior.*

Expect back button to work on first hit. I have to hit back twice vs once in the mobx-shop demo after I enter a query to filter the list.

*Steps to reproduce the problem.*

1. enter query and hit enter
2. hit back (works)
3. hit forward
4. back broken now

*Specifications like the version of the project, operating system, or hardware.*

OSX El Capitan v10.11.6 - Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by nareshbhatia** [comment]
@derek-knox, you get the prize for finding the first bug in mobx-state-router :-).

When comparing current URL with router's state, I was not considering search parameters. This was
causing a spurious `history.push()`. This has been fixed in mobx-state-router 1.0.1. You can now try mobx-shop and it should work perfectly!
